version: "3"

services:

  db:
    image: postgis/postgis:15-master
    env_file:
      - .env

  app:
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
