# Generated by Django 4.1.5 on 2023-01-29 21:44

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plantinfos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Garden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Name"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Geom"
                    ),
                ),
                (
                    "geo_zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plantinfos.hardinesszone",
                        verbose_name="Geographic zone",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "garden",
                "verbose_name_plural": "gardens",
            },
        ),
        migrations.CreateModel(
            name="Planting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="Location",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plantinfos.plants",
                        verbose_name="Plant",
                    ),
                ),
            ],
            options={
                "verbose_name": "garden space",
                "verbose_name_plural": "garden spaces",
            },
        ),
        migrations.CreateModel(
            name="Operations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date"
                    ),
                ),
                (
                    "operation",
                    models.ManyToManyField(to="plantinfos.operationslist"),
                ),
                (
                    "planting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mygarden.planting",
                        verbose_name="Plant",
                    ),
                ),
            ],
            options={
                "verbose_name": "garden space",
                "verbose_name_plural": "garden spaces",
            },
        ),
        migrations.CreateModel(
            name="GardenSpaces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Name"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Geom"
                    ),
                ),
                (
                    "garden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mygarden.garden",
                        verbose_name="Garden",
                    ),
                ),
            ],
            options={
                "verbose_name": "garden space",
                "verbose_name_plural": "garden spaces",
            },
        ),
    ]
