# Generated by Django 4.1.5 on 2023-01-29 21:44

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Condition",
                "verbose_name_plural": "Conditions",
            },
        ),
        migrations.CreateModel(
            name="HardinessZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Name"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Geom"
                    ),
                ),
            ],
            options={
                "verbose_name": "hardiness zone",
                "verbose_name_plural": "hardiness zones",
            },
        ),
        migrations.CreateModel(
            name="OperationsList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Operation",
                "verbose_name_plural": "Operations list",
            },
        ),
        migrations.CreateModel(
            name="Plants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sci_name",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Scientific name",
                    ),
                ),
                (
                    "common_name",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Common name",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plantinfos.plants",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant",
                "verbose_name_plural": "Plants list",
            },
        ),
        migrations.CreateModel(
            name="PlantOperations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_month",
                    models.IntegerField(verbose_name="Start month"),
                ),
                (
                    "start_day",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Start day"
                    ),
                ),
                ("end_month", models.IntegerField(verbose_name="End month")),
                (
                    "end_day",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="End day"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Instructions"
                    ),
                ),
                (
                    "conditions",
                    models.ManyToManyField(
                        to="plantinfos.conditions", verbose_name="Conditions"
                    ),
                ),
                (
                    "geo_zone",
                    models.ManyToManyField(to="plantinfos.hardinesszone"),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plantinfos.operationslist",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plantinfos.plants",
                    ),
                ),
            ],
            options={
                "verbose_name": "plant operation",
                "verbose_name_plural": "plant operations",
            },
        ),
    ]
